# Tensors

Similar to arrays and matrices. We use these tensors to encode the inputs and outputs of a model as well as the parameters (w & b).

Very similar to NumPys ndarrays. The difference being that tensors can be run on GPUs and are generally much more efficient.

In [2]:
import torch
import numpy as np

## Initialising a Tensor

Tensors can be initialised in numerous ways:

#### Directly from Data:
Tensors can be created directly from data. The data type is auto inferred.

In [7]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

#### From a NumPy array

In [9]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

#### From another tensor:
The new tensor retains properties(shape, dtype) of the argument tensor, unless explicitly overriden.

In [12]:
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor: \n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random Tensor: \n {x_rand} \n')


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7852, 0.9725],
        [0.4002, 0.0010]]) 



#### With random or constant values:
'shape' is a tuple of tensor dimensions, in the functions below it determines the dimensionality of the output tensor

In [14]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3974, 0.8081, 0.3711],
        [0.8801, 0.9310, 0.0297]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor
Tensor attributes describe their shape, dtype, and device on which they are stored

In [19]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Dtype of tensor: {tensor.dtype}")
print(f"Device the tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Dtype of tensor: torch.float32
Device the tensor is stored on: cpu


## Operations on Tensors
There are over 100 tensor operations. Each can be run on the GPU. By default they are on the CPU and you will have to change them:

In [21]:
if torch.cuda.is_available():
    tensor.tensor.to("cuda")

#### Standard NumPy like indexing and slicing:

In [23]:
tensor = torch.ones(4,4)
print(f"First Row: {tensor[0]}")
print(f"First Column: {tensor[:, 0]}")
print(f"First Column: {tensor[..., -1]}")
tensor[:,1]=0
print(tensor)

First Row: tensor([1., 1., 1., 1.])
First Column: tensor([1., 1., 1., 1.])
First Column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### torch.cat -> Joining tensors
Use torch.cat to concatenate a sequence of tensors along a given dimension. Torch.stack is similar but slightly different to torch.cat

In [26]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### Arithmetic Operations

In [28]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

#### Single-element tensors
if you have a one element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item()

In [30]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


#### In-place operations
Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example:

In [31]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

# note:
# In-place operations save some memory,
# but can be problematic when computing derivatives because of an immediate loss of history.
# Hence, their use is discouraged.

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
